### ISSUE TITLE
[BUG] Not updating workshop items after update to 1.11.5

### ISSUE THREAD

**Issue by TraceIronworks** [egebilecen/PZServerDiscordBot#169] opened 2024-10-01 11:25 UTC
**Describe the bug**
After the bot timer for workshop update passes it does nothing. Either doesn't notice or doesn't trigger the restart.

**To Reproduce**
Wait for a workshop item to update

**Expected behavior**
Bot to trigger warnings and after x minutes restart and update mod. 

**Screenshots**

**Additional context**
It took a long time for my host to add your update to their site so I could update. Now that I look back I've been doing manual workshop updates since I updated on the 10th of September. 1.11.4 seemed to work perfectly for us, not sure why 1.11.5 is missing updates.  

Thanks as always!

**Comment by egebilecen** [comment] 2024-10-01 13:38
Hello, version 1.11.5 only updated English localization. There have been no code change. The problem is most likely related to your host, unfortunately. If you can please attach the log file so I can take a look.

**Comment by TraceIronworks** [comment] 2024-10-01 14:03
I'll put in the log request, I remember I had issue with the host a few versions back. Thanks!

**Comment by egebilecen** [comment] 2024-10-01 14:04
No problem 😊

**Comment by TraceIronworks** [comment] 2024-10-01 14:06
Log is 82mb lol let me upload to google.

**Comment by TraceIronworks** [comment] 2024-10-01 14:08
https://drive.google.com/file/d/1rhLNCFSdYgmmN9EgJFrmS5i-K07an0ud/view?usp=sharing

**Comment by egebilecen** [comment] 2024-10-01 14:27
> https://drive.google.com/file/d/1rhLNCFSdYgmmN9EgJFrmS5i-K07an0ud/view?usp=sharing

I do believe this problem is related to your host. Give it couple days and see if it will be fixed. I just tested the bot and steam responds me without any problem.

**Closed by egebilecen** 2024-10-01 14:27 UTC
Labels: bug

**Comment by TraceIronworks** [comment] 2024-10-01 17:22
Much appreciated I'll poke at the host and see if they did anything.

**Comment by egebilecen** [comment] 2024-11-06 18:48
> Hello again Ege! Sorry to open an old issue I've moved server from PingPerfect to an Ubuntu host so I cant use the bot anymore but wanted to thank you again for the work and updates you provided. Good luck out there!
> 
> Coot of Cooterville PZ server.

I hope the bot served you well in the span you used it. Thank you for your kind comment. 😊
