### ISSUE TITLE
Possible issue with adding workshop mods

### ISSUE THREAD

**Issue by Recon224** [egebilecen/PZServerDiscordBot#96] opened 2023-09-06 16:51 UTC
Hi, I have been using your bot for over a month now and have had a great experience so far. However, I'm not sure if it is working as intended or not but when I updated the other day to v1.10 and attempted to add a workshop mod from the discord command line, the servertest.ini lines for ModID= and WorkshopID= were completely erased and replaced with the one workshop item that was being added through the command. 

Therefore, I ended up with "ModID=NameofMod" and "WorkshopID=123456789" (examples only) instead of the bot adding the mod to the end of the 200+ list I had previously. Just wanted to give a heads up in case this isn't working exactly as planned.

**Comment by egebilecen** [comment] 2023-09-06 17:11
Thanks for the heads up!

@DomicidalDesigns you might want to check this, otherwise I will need to revert the changes. :(

**Comment by DomicidalDesigns** [comment] 2023-09-06 17:32
Thanks for reporting this. I am sorry that you lost the other mods in the file. I have many mods too and I imagine that would be very frustrating.

I'll look into this and try to get it fixed.

@Recon224, Do you remember the mod that you tried adding? It'll be helpful to replicate the issue.

**Comment by Recon224** [comment] 2023-09-06 17:39
No problem! Happy to help in any way I can. 

Here is the exact command I executed yesterday:

!add_workshop_mod https://steamcommunity.com/sharedfiles/filedetails/?id=2744797858

**Comment by DomicidalDesigns** [comment] 2023-09-06 21:54
> No problem! Happy to help in any way I can.
> 
> Here is the exact command I executed yesterday:
> 
> !add_workshop_mod https://steamcommunity.com/sharedfiles/filedetails/?id=2744797858

@Recon224 
Thank you. I haven't been able to reproduce the issue at this time, but I am still evaluating.

**Comment by DomicidalDesigns** [comment] 2023-09-07 17:19
@Recon224, can you provide the list of mods and workshopitems from the config *.ini file from the backup? It should be under "backups\startup\backup_1.zip\Server\servertest.ini" or similar.

If you don't have any passwords/private info stored in the .ini it would be helpful if you can share the entire file :)

**Comment by egebilecen** [comment] 2023-09-08 20:42
@DomicidalDesigns did you test this feature while server was running? Maybe server is opening the config file and doesn't close the handle until the server is stopped. Thus writing to file while it having handle causing issues? I'm just spitballing. Because afaik we wouldn't able to get a handle to a file while they are in use (unless they specified file sharing options which is unlikely for server) so it shouldn't be the case but can't be too careful.

**Comment by egebilecen** [comment] 2023-11-13 09:33
I am closing this issue as there have been no update for a long time.

**Closed by egebilecen** 2023-11-13 09:33 UTC
Labels: bug
